export const CARD_LOAD_REQUEST = 'CARD_LOAD_REQUEST';
export const CARD_LOAD_SUCCESS = 'CARD_LOAD_SUCCESS';
export const CARD_LOAD_FAILURE = 'CARD_LOAD_FAILURE';
export const CARD_SAVE_REQUEST = 'CARD_SAVE_REQUEST';
export const CARD_SAVE_SUCCESS = 'CARD_SAVE_SUCCESS';
export const CARD_SAVE_FAILURE = 'CARD_SAVE_FAILURE';